# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.0
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.19.1
        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  omglol:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mcornick/clilol
      env:
        CLILOL_ADDRESS: ${{ secrets.OMG_LOL_API_ADDR }}
        CLILOL_APIKEY: ${{ secrets.OMG_LOL_API_KEY }}
        CLILOL_EMAIL: ${{ secrets.OMG_LOL_API_EMAIL }}
    steps:
      - run: list purls
