# when new now page is added push to omg.lol
on:
  push:
    paths:
      - content/now/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: diff
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        run: |
          content=`cat ${{steps.diff.outputs.added}}`
          echo ${content}
